import { Config, QuizValues } from "../store/types";
import background_desktop from "../assets/background_desktop.jpg";
import mobile_desktop from "../assets/background_mobile.jpg";

import question_1 from "./../assets/question_1.png";
import question_2 from "./../assets/question_2.png";
import question_3 from "./../assets/question_3.png";
import question_4 from "./../assets/question_4.png";
import question_5 from "./../assets/question_5.png";
import loader from "./../assets/loader.png";

export const quizValues: QuizValues = {
  1: {
    img: question_1,
    question: "Playing sports",
    options: [
      {
        option: "Football",
        point: 3,
        keyWords: [
          "year",
          "old",
          "cask",
          "strength",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "travel",
          "spray",
          "case",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "gold",
          "zinc",
          "toned",
          "hair",
          "set",
          "edition",
          "evolution",
          "set",

          "Pure",
          "Annual",
          "easter",
          "bowl",
        ],
      },
      {
        option: "Golf",
        point: 1,
        keyWords: [
          "travel",
          "spray",
          "case",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "gold",
          "zinc",
          "toned",
          "hair",
          "set",
          "edition",
          "evolution",
          "set",
          "travel",
          "spray",
          "case",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "gold",
          "zinc",
          "toned",
          "hair",
          "set",
          "edition",
          "evolution",
          "set",
        ],
      },
      {
        option: "Athletics",
        point: 2,
        keyWords: [
          "Easter",
          "egg",
          "cup",
          "Art",
          "red",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "perfume",
          "mist",
          "diffuser",
          "black",

          "edition",
          "evolution",
          "set",
          "travel",
          "spray",
          "case",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "gold",
          "zinc",
          "toned",
          "hair",
          "set",
          "edition",
          "evolution",
          "set",
        ],
      },
    ],
  },
  2: {
    img: question_2,
    question: "Food/Drink",
    options: [
      {
        option: "Asian",
        point: 3,
        keyWords: [
          "Silk",
          "Oil",
          "Free",
          "Photo",
          "Edition",
          "Foundation",
          "Bois",
          "large",

          "edition",
          "evolution",
          "set",
        ],
      },

      {
        option: "Chinese",
        point: 3,
        keyWords: [
          "Sloe",
          "gin",
          "series",
          "pistachio",
          "and",
          "sea",
          "salt",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "chocolate",

          "edition",
          "evolution",
          "set",
        ],
      },

      {
        option: "British",
        point: 3,
        keyWords: [
          "Easter",
          "egg",
          "cup",
          "Art",
          "red",
          "perfume",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "mist",
          "diffuser",
          "black",

          "edition",
          "evolution",
          "set",
        ],
      },
      {
        option: "European",
        point: 3,
        keyWords: [
          "Pure",
          "Malt",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "Rhubarb",
          "Men",
          "Pure",
          "Havane",
          "Edited",
          "single",
          "malt",
          "whisky",
          "piece",
          "Chocolate",
          "collection",
          "Nine",
          "Sloe",
        ],
      },

      {
        option: "American",
        point: 1,
        keyWords: [
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
        ],
      },
      {
        option: "Cocktails",
        point: 2,
        keyWords: [
          "candle",
          "indoor",
          "outdoor",
          "edition",
          "Terracotta",
          "Le",
          "Parfum",
          "Anniversary",
          "Moisturizing",
          "Pasha",
          "Noire",
          "Sport",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "Toilette",
          "Aurora",
          "limited",
          "vodka",
          "toilette",
          "The",
        ],
      },
    ],
  },
  3: {
    img: question_3,
    question: "Watching TV",
    options: [
      {
        option: "Comedy",
        point: 3,
        keyWords: [
          "Leo",
          "Tolstoy",
          "Writers",
          "ballpoint",
          "pen",
          "JFK",
          "Special",
          "rollerball",
          "Honore",
          "Balzac",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
        ],
      },
      {
        option: "Dramas",
        point: 1,
        keyWords: [
          "Leo",
          "Tolstoy",
          "Writers",
          "ballpoint",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "pen",
          "JFK",
          "Special",
          "rollerball",
          "Honore",
          "Balzac",
        ],
      },
      {
        option: "Documentaries",
        point: 2,
        keyWords: [
          "Mixology",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "Mad",
          "Med",
          "Circon",
          "highball",
          "glasses",
          "of",
          "two",
          "2",
          "custom",
          "gabe",
          "jacket",
          "Leo",
          "Tolstoy",
          "Writers",
          "ballpoint",
          "pen",
          "JFK",
          "Special",
          "rollerball",
          "Honore",
          "Balzac",
        ],
      },
    ],
  },
  4: {
    img: question_4,
    question: "They prefer...",
    options: [
      {
        option: "carrot juice",
        point: 3,
        keyWords: [
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "Set",
          "Robinson",
          "stainless",
          "steel",
          "watch",
          "Great",
          "Characters",
          "Miles",
          "Davis",
        ],
      },
      {
        option: "beer",
        point: 1,
        keyWords: [
          "Rollerball",
          "Grey",
          "Goose",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "La",
          "Nuit",
          "des",
          "toiles",
          "edition",
          "evolution",
          "set",
        ],
      },
      {
        option: "wine",
        point: 2,
        keyWords: [
          "Platinum",
          "Velvet",
          "Shadow",
          "stick",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "studded",
          "leather",
          "skate",
          "shoes",
          "Baies",
          "noir",
        ],
      },
    ],
  },
  5: {
    img: question_5,
    question: "Out on the town",
    options: [
      {
        option: "Clubbing",
        point: 3,
        keyWords: [
          "savoury",
          "crackers",
          "tin",
          "450g",
          "edition",
          "evolution",
          "set",
          "Atkinsons",
          "Silken",
          "Favour",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "David",
          "Downtown",
        ],
      },
      {
        option: "Cinema",
        point: 1,
        keyWords: [
          "Figuier",
          "Highland",
          "Park",
          "edition",
          "evolution",
          "set",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "Ice",
          "Black",
          "Orchid",
          "Lalique",
          "Guess",
        ],
      },
      {
        option: "Pub",
        point: 2,
        keyWords: [
          "three",
          "One",
          "bronzing",
          "Edit",
          "Eyeshadow",
          "Palette",
          "Evolution",
          "White",
          "Limited",
          "Rhubarb",
          "Men",
          "Pure",
          "powder",
          "SS16",
          "silicone",
          "Plage",
          "Protective",
          "Sun",
          "Veil",
          "edition",
          "evolution",
          "set",
        ],
      },

      {
        option: "Group activities",
        point: 2,
        keyWords: [
          "Pro",
          "Refill",
          "Sponges",
          "Automatic",
          "Applicator",
          "Specs",
          "Four",
          "sunglasses",
          "specs",
          "edition",
          "evolution",
          "set",
        ],
      },
      {
        option: "Shopping",
        point: 2,
        keyWords: [
          "Bond",
          "Street",
          "Cologne",
          "Rosa",
          "Nobile",
          "parfum",
          "edition",
          "evolution",
          "set",
          "refill",
        ],
      },
    ],
  },
};

export const configurations: Config = {
  images: {
    background: {
      desktop: background_desktop,
      mobile: mobile_desktop,
    },
    loader: loader,
    image1: "string",
  },
  notes: [
    "Granny will be surprised",
    "Mummy or auntie",
    "Nice one for brother",
  ],
  uiText: {
    descriptions: {
      header: "lets celebrate mothers day",
      result: "",
      box: "Let our expert artificial intelligence hosted on the blockchain network to choose your Mother's day gift",
    },
    titles: {
      holidayName: "Mothers day",
      calendarEventFile: "my_gifts_reminder",
      copyLink: "Add to basket",
      saveReminderBtn: "Set a reminder",
      selection: "save your personal top {NUMBER} of Mothers Day {GIFT}",
      savePdfBtn: "Download",
      result: "Genereting your personal gift selection...",
      box: "Create you hamper for someone special",
    },
  },
  reminders: {
    // "Early winter": {
    end: [2023, 12, 10],
    url: "https://www.selfridges.com/GB/en/",
    start: [2023, 12, 1],
    title: "It's time to look at your guide at Selfridges!",
    location: "Selfridges, Oxford street",
    // },
    // "Almost Mothers Day eve": {
    //   end: [2023, 12, 15],
    //   url: "https://www.selfridges.com/GB/en/",
    //   start: [2023, 12, 10],
    //   title: "Your favourite Mothers Day party at Selfridges! Stay tuned",
    //   location: "Selfridges, Oxford street",
    // },
    // "Twice!": undefined,
  },
  tips: [
    {
      text: "make them play",
      desc: "Look at our gaming guide!!",
      keyWords: ["Funny", "game"],
    },
    {
      text: "Make urself warm",
      desc: "Look at our gaming guide!!",
      keyWords: ["sweatshirt", "warm"],
    },
    {
      text: "selfridges candies guide",
      desc: "This amazing brand has also so manyyy sweets",
      keyWords: ["chocolate", "bisquits", "truffles"],
    },
    {
      text: "some tips for you",
      desc: "This amazing brand has sale!",
      keyWords: ["parfum"],
    },
  ],

  quizValues,

  colours: {
    tip: "#E694A3",
    mainBtn: "rgb(255,226,85)",
    tip1: "#2E2D2B",
    tip2: "#2E2D2B",
  },
};
